### ISSUE TITLE
Changes to final scores report to aide head judges

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#440]
Add a report to the reporting page that shows the top teams by performance for each division. This will make it clear to the head judge who wins the report performance award.

**Comment by eengstrom** [comment]
> Add a report to the reporting page that shows the top teams by
> performance for each division. This will make it clear to the head
> judge who wins the __report__ performance award.

[emphasis mine]

I'm not sure what you mean, especially by the "report performance award."

If you mean what I think you mean, then what you are suggesting is exactly what I wanted last year, but for the life of me I can't find a bug report about this.  I must never have created it.

Regardless, what I thought would be most helpful would be to **highlight** or __underline__ the top scores in each subjective (and numeric) category on the final computed scores report.  I know that Norm and I typically circle or otherwise mark them anyway, searching by hand for the highest.  I don't think we need a new report.

This doesn't help at state as much mostly because of the different judging groups in a single division.  That is unless we can put a Judging Group indicator ("A" or "*", "B" or "%", etc) next to each team by their group.  That might get too complicated.

Is this similar to what you meant?

**Comment by jpschewe** [comment]
I don't think the head judges will notice an underline on the sheet. Besides they typically want to know the top 3 or so and need to announce one. I already have a report that shows the teams in each subjective category sorted by score, I just need one for performance like what shows up on the scoreboard.

**Comment by eengstrom** [comment]
As a head judge, I respectfully disagree.  Highlighting the tops score on the final report is a big win.
If you want to do the other thing too, that's fine, but I really never use it because I dislike having so many pieces of paper.  I want just one with the top score(s) in each category in each division but ** on only one piece of paper **.

**Comment by jpschewe** [comment]
Fair enough. Would it make sense to have the top score bold and the performance scores that meet the percentage criteria underlined?

If you're going to choose the second highest subjective score for the award, how do you determine that from the final computed scores sheet?

**Comment by eengstrom** [comment]
> Would it make sense to have the top score bold

Yes

> and the performance scores that meet the percentage criteria underlined?

Sure.  Though I think those two issues are orthogonal.

> If you're going to choose the second highest subjective score for
> the award, how do you determine that from the final computed scores
> sheet?

Well, if I can ask for anything, you could put a rank number in a
little circle next to each of the top "n" scores.  I suppose you could
do all of them, but I really only care about the top 3 or maybe five.
But only bold the first / highest then.

e.g,  (some catagories ignored and simplified):
    
    Team     Project    Design     Robot Game
    Foo        99          40         100
             *140*(1)     100 (3)      60
    
    Bar        88          60         200
              120 (2)    *140*(1)      80
    
    Red        77          20         300
              100 (3)      60         100 (3)
    
    Blue       66          50         400
               90         120 (2)     120 (2)
    
    Green      55          30         500
               80          60        *140*(1)
    

While we are at it, a key on the report would be nice that says
something like:  Scores in each category are averaged to 100 with a
standard deviation of 20 (or is it 25?).

**Comment by jpschewe** [comment]
The reason I asked about the performance percentage is that I can't use
bold for both, otherwise you don't know what bold means.

I can see about the other changes to the report.

**Comment by eengstrom** [comment]
Ok, well bold or italic or underline or red or whatever.  Something unique for each "axis" of concern.
