### ISSUE TITLE
Use mDNS

### ISSUE THREAD

**Issue by codetheweb** [jpschewe/fll-sw#527]
Use an mDNS address for the server.  This would get configured in the setup script, which would give the computer an mDNS address so that all other computers and tablets could reach it at a much more memorable address like server.local or similar.

## Linux
mDNS is automatically on in recent versions of Ubuntu, but the name can be edited by changing the `host-name` parameter in `/etc/avahi/avahi-daemon.conf`.

## Windows
Windows is a good deal harder, because it doesn't come with mDNS support.  We would have to compile and install Avahi.  Since most machines are Linux and this is a non-essential feature, it's probably not a deal breaker not to include Windows support.

**Comment by jpschewe** [comment]
It would be nice if this worked on Windows as well. Especially without special configuration. 

Is it possible that the Java software could be the mDNS broadcast and not rely upon avahi?

Also will the tablets support it? We mostly use Android tablets, but since people being iPads as well.

**Comment by jpschewe** [comment]
I tested the tablets and windows at a tournament today; they didn't work. It's great fort Linux, but not so much for the others.

Eventually it would be nice to have something that the public can user as well.

**Comment by codetheweb** [comment]
Alright, I wasn't sure if it would work on Android tablets.

Maybe the router could give the server a static address instead?

**Comment by jpschewe** [comment]
That is something that I have thought about as well. I would like to get
all of the MAC addresses for all of the laptops into all routers with
static addresses.

**Comment by jpschewe** [comment]
@jjkoletar tells me that if we run dnsmasq on the routers that may allow systems that don't support multicast DNS to work. I'd like to see a proof of concept before rebuilding all of the Minnesota routers with custom firmware.

**Comment by jjkoletar** [comment]
The trick comes down to using dnsmasq and the router itself as a shim for Windows and the Android tablets.

OpenWRT comes with dnsmasq in the box, as well as with a (to quote my friend) "largely undocumented" mDNS utility: https://wiki.openwrt.org/doc/howto/zeroconf#mdns

Periodically (every 5 minutes maybe) we can dump the contents of the router's mDNS cache into /etc/hosts (or some other hostname -> IP mapping file that we tell dnsmasq to look at). This means that we then get a real DNS server to resolve locally discovered hostnames for clients that don't natively support mDNS.

**Comment by jpschewe** [comment]
Can you get this up and running on a router and show me the configuration so that I can use it on the other router?
Our current routers are Linksys E1200 and Netgear WNR200v5.

**Comment by jjkoletar** [comment]
Holy crap, it can be even simpler than I imagined:

The primary step is to use dnsmasq as the DHCP/DNS server. The key feature of dnsmasq is that it will resolve hostnames to the IP given through DHCP over DNS.

Setup: A home router running a default install of OpenWRT on a Linksys E3000 (that I'll bring to sectionals tomorrow if you want to play around with it with me).

<img width="463" alt="screen shot 2017-01-27 at 8 36 06 pm" src="https://cloud.githubusercontent.com/assets/735098/22393638/44e1a7da-e4d0-11e6-852d-3248c3d25eb2.png">

`Corrupt-Bargain-Election` is my laptop's hostname, `Dank-Memes` is my phone's hostname.

```
Corrupt-Bargain-Election:~ jjkoletar$ dig @192.168.1.1 Dank-Memes.lan

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.1 Dank-Memes.lan
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39478
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;Dank-Memes.lan.			IN	A

;; ANSWER SECTION:
Dank-Memes.lan.		0	IN	A	192.168.1.236

;; Query time: 0 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Jan 27 20:32:18 2017
;; MSG SIZE  rcvd: 48

Corrupt-Bargain-Election:~ jjkoletar$ dig @192.168.1.1 Corrupt-Bargain-Election.lan

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.1 Corrupt-Bargain-Election.lan
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36719
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;Corrupt-Bargain-Election.lan.	IN	A

;; ANSWER SECTION:
Corrupt-Bargain-Election.lan. 0	IN	A	192.168.1.165

;; Query time: 1 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Jan 27 20:33:03 2017
;; MSG SIZE  rcvd: 62

```


**Why we don't need anything more:**
For the Tournament Scoring Coordinator, the laptop which is acting as the server has a well-known unique identifier, e.g. `fll-53`. If I remember correctly, this is also the hostname of the machine. Because dnsmasq will answer DNS queries for the `.lan` domain, and answer them by checking against current DHCP leases, we can simply navigate the tablets to `http://fll-53.lan:9080/fll-sw/`. Then, if `fll-53` is assigned a new IP, DNS queries for the hostname will be answered with the new IP for that hostname.


It almost seems too simple. Let me know if you can think of any reason that running dnsmasq alone and using the laptop's hostname + `.lan` wouldn't work.

**Comment by jpschewe** [comment]
Biggest reason I can see right now is that the routers we have aren't
listed as supported by OpenWRT.

Yes all of the computers have unique hostnames. If the router can do
dynamic DNS like this, then it should work.

I won't be at the sectional until sometime in the afternoon.

Sent from my mobile device

On Jan 27, 2017 20:41, "Jeremy" <notifications@github.com> wrote:

Holy crap, it can be even simpler than I imagined:

The primary step is to use dnsmasq as the DHCP/DNS server. The key feature
of dnsmasq is that it will resolve hostnames to the IP given through DHCP
over DNS.

Setup: A home router running a default install of OpenWRT on a Linksys
E3000 (that I'll bring to sectionals tomorrow if you want to play around
with it with me).

[image: screen shot 2017-01-27 at 8 36 06 pm]
<https://cloud.githubusercontent.com/assets/735098/22393638/44e1a7da-e4d0-11e6-852d-3248c3d25eb2.png>

Corrupt-Bargain-Election is my laptop's hostname, Dank-Memes is my phone's
hostname.

Corrupt-Bargain-Election:~ jjkoletar$ dig @192.168.1.1 Dank-Memes.lan

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.1 Dank-Memes.lan
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39478
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;Dank-Memes.lan.			IN	A

;; ANSWER SECTION:
Dank-Memes.lan.		0	IN	A	192.168.1.236

;; Query time: 0 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Jan 27 20:32:18 2017
;; MSG SIZE  rcvd: 48

Corrupt-Bargain-Election:~ jjkoletar$ dig @192.168.1.1
Corrupt-Bargain-Election.lan

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.1 Corrupt-Bargain-Election.lan
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36719
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;Corrupt-Bargain-Election.lan.	IN	A

;; ANSWER SECTION:
Corrupt-Bargain-Election.lan. 0	IN	A	192.168.1.165

;; Query time: 1 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Jan 27 20:33:03 2017
;; MSG SIZE  rcvd: 62


*Why we don't need anything more:*
For the Tournament Scoring Coordinator, the laptop which is acting as the
server has a well-known unique identifier, e.g. fll-53. If I remember
correctly, this is also the hostname of the machine. Because dnsmasq will
answer DNS queries for the .lan domain, and answer them by checking against
current DHCP leases, we can simply navigate the tablets to
http://fll-53.lan:9080/fll-sw/. Then, if fll-53 is assigned a new IP, DNS
queries for the hostname will be answered with the new IP for that hostname.

It almost seems too simple. Let me know if you can think of any reason that
running dnsmasq alone and using the laptop's hostname + .lan wouldn't work.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jpschewe/fll-sw/issues/527#issuecomment-275821737>, or mute
the thread

**Comment by jpschewe** [comment]
We are moving toward using online servers all of the time, so this need goes away.
