### ISSUE TITLE
Streamlined 2 server import/export

### ISSUE THREAD

**Issue by jpschewe** [jpschewe/fll-sw#670]
Issue #656 created instructions for using 2 servers. Issue #657 is for the backend computer person to be able to do partial merges. This issue is to make the process easier for the day of the tournament. 

Features
  * there should be an explicit export button to download the performance data
    * this can actually be a full database dump
  * On export, warn if there are subjective scores or judges entered for the current tournament
    * will need to redirect to a warning page if this is true
  * Add an import button that checks the import to see that the tournament name matches and then pulls in all of the performance data using the partial import mechanism from #657 
  * the import should warn if there are performance scores that will be overwritten

**Comment by jpschewe** [comment]
If the 2 server model works well in Minnesota for the 2018/2019 season, this is something that should be implemented late in the season or for the 2019/2020 season.

**Comment by jpschewe** [comment]
@rudolph4404 you mentioned that you are interested in this.

**Comment by rudolph4404** [comment]
Been thinking about this and what's happened in the past.
I came up with...

All imports should be proceeded by an automatic export.

Exports should always be the full tournament (database?). This would allow us to easily unwind a bad import or other edit.

Export names should include the tournament name, date, timestamp and maybe an optional tag (ex: "seeding rounds"). Stop using database(#).flldb and subjective-data(#).fll. This is confusing. If there is a hole in the # sequence, the current export fills it in rather than add a new max #.

Filters should only be available on the import:
+ Who: whole database, tournament, division, team(s)
+ What: everything, team info, seeding round(s), head-to-head round(s), judge(s), judging category(ies)
+ Type: merge (missing only), overwrite
** Extra brownie points to the coder for allowing the picking of multiple teams, rounds, judges or categories. **

-Chuck

**Comment by jpschewe** [comment]
The names of the files is determined by the browser. So there isn't a lot we can do about that.

The import filters are good ideas, we'll need to keep that in mind when this is implemented.

**Comment by jpschewe** [comment]
That suggestion has been made and I've been told it's too difficult.

The right answer is to have a real export and import.

**Comment by jpschewe** [comment]
The names of the download files can be specified by setting the header `Content-Disposition: attachment; filename="downloaded.pdf"`
