### ISSUE TITLE
Changes to City Shaper Score Sheet

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#760]
We need a check box or YES/NO for Passing Small Inspection Area

M03 - specify Supported by Axel "A"
M04 - specify supporter by Branch "B"

Default start for Precision tokens?  Better to be at 6?

M12 - Color Matching in Circles - in reviewing rules there are actually only 3 choices.  Can we have Red, White, Tan as choices and they circle any placement in those circles instead of 0-3  I think that will make it easier for Ref - 
Also Color matching must be COMPLETELY IN.

M06 - add Lifted and Independent

M05 (Treehouse) and M12 (Color matching & Levels) impact one another.  Only have a total of 16 buildings so if they put some in trees it will impact how many levels are possible.  Hard to control because some buildings are 2 levels and some are 1 level

**Comment by jpschewe** [comment]
I see the missing checkbox for small inspection area. I will add that and fix the bonus.

For m03, do you want the text changed or is this a score change?

M04 same question as m03

I can change the default for precision tokens

M12 I can't name the values separately unless I make them separate yes/no goals. The refs should be able to count circles.

M06 is this a text change?

For the m05 and M12 interaction I'm not sure. If there are only 16 buildings, then can you only have 16 levels?

**Comment by jpschewe** [comment]
Talked to Jeannie.

M03 instead of "alex" use "Alex A"

M04 instead of "Branch" use "Branch B"

M12 - Make it 3 separate yes/no goals for "Red", "Tan", "White"  (in order). Also add "Completely In" to the text of each.

M06 instead of "Lifted" use "Lifted and Independent"

M05 and M12 interaction, turns out we can't check this. There just isn't enough information. This will need to be brought up in Refs training.

On M01 cannot score m01_flags without m01_robot_bridge.
