### ISSUE TITLE
Innovation Project Rubric - no team name

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#763]
This new name for Project is "Innovation Project"

When this is changed using the Editor the title on the page "Innovation Project" wraps and knocks "Team Name"  off the page!  Compare to Core Value Rubric
[subjective-project.pdf](https://github.com/jpschewe/fll-sw/files/3580802/subjective-project.pdf)
[subjective-core_values.pdf](https://github.com/jpschewe/fll-sw/files/3580805/subjective-core_values.pdf)

I am changing to xml file right now and will send you an updated version later today.

**Comment by jpschewe** [comment]
Longer category names are going to be a problem. Do you want the longer category or they longer team name?

**Comment by jeanniebadger** [comment]
Could we move the Team Number title and field over to the right?  We have some physical space on the rubric for that.

**Comment by jeanniebadger** [comment]
I want both!!

The official title of project from FIRST is "Innovation Project" so I think we have to have that on the rubric.

**Comment by jpschewe** [comment]
Agreed, the name of the category needs to match that from FIRST. I'll see what I can do about the layout of the sheet header.

**Comment by jpschewe** [comment]
The problem is that the layout is a table and the largest table cell drives the sizing. If we shrink the "Team Number" cell, then the "Team Name" cell gets shrunk as well. I may be able to nest tables differently to give more space though. 

The attached PDFs have the cell borders drawn to help visualize the issue.
[subjective-core_values-1.pdf](https://github.com/jpschewe/fll-sw/files/3586602/subjective-core_values-1.pdf)
[subjective-project-1.pdf](https://github.com/jpschewe/fll-sw/files/3586603/subjective-project-1.pdf)
