### ISSUE TITLE
Awards printout typo - when to add 's' to make level plural

### ISSUE THREAD

**Issue by jeanniebadger** [jpschewe/fll-sw#812]
Teams advancing to State (not Teams advancing to States)

**Comment by jpschewe** [comment]
@jeanniebadger  it's not exactly a typo. I add a "s" to the end of the value that's put into the next level field for the tournament. This works with Regional -> Sectional, but as you noticed doesn't work for Sectional -> State. I could remove this appending of "s" from the next level and leave it up to the user to put that information in the tournaments setup. Can you take a look at the add/edit tournaments page and let me know what you think would be most user friendly?
Realize that I don't want to hardcode the names of the levels into the software because they change and other organizations will have different levels, or none at all.

**Comment by jpschewe** [comment]
Another alternative is that instead of saying "Advancing to Sectionals" or "Advancing to State", I could say "Advancing to the next tournament". That would make this easier. What do you think @jeanniebadger ?

**Comment by jeanniebadger** [comment]
We can edit the tournament name if needed.  Let's not add the "s".  We can say the next tournament is Sectional not Sectionals
